import type { Scholarship } from "@/types/database";

/**
 * Catalogue de repli utilisé UNIQUEMENT quand Supabase n'est pas configuré,
 * afin que le parcours d'évaluation reste démontrable hors base de données.
 * La source de vérité en production reste `supabase/seed.sql` (50 programmes).
 */
type CatalogSeed = Pick<
  Scholarship,
  | "title"
  | "country"
  | "institution"
  | "degree_levels"
  | "eligible_fields"
  | "min_gpa_20"
  | "max_age"
  | "funding_coverage"
  | "deadline_month"
  | "language_requirements"
  | "annual_cost_xaf"
  | "fully_funded"
>;

const SEED: CatalogSeed[] = [
  {
    title: "Bourse du Gouvernement Turc — Türkiye Bursları",
    country: "Turquie",
    institution: "Université d'État (réseau YÖK)",
    degree_levels: ["Licence", "Master", "Doctorat"],
    eligible_fields: ["Informatique", "Génie Civil", "Génie Électrique", "Médecine", "Business", "Agronomie", "Droit", "Sciences Économiques"],
    min_gpa_20: 13.0,
    max_age: 30,
    funding_coverage: "100% Scolarité + Allocation + Logement + Billet",
    deadline_month: "Février",
    language_requirements: "Turc (année préparatoire offerte) ou anglais B2",
    annual_cost_xaf: 0,
    fully_funded: true,
  },
  {
    title: "Programme MEXT — Étudiant Recherche",
    country: "Japon",
    institution: "Universités nationales japonaises",
    degree_levels: ["Licence", "Master", "Doctorat"],
    eligible_fields: ["Informatique", "Génie Civil", "Génie Électrique", "Agronomie", "Sciences de l'Environnement"],
    min_gpa_20: 14.0,
    max_age: 35,
    funding_coverage: "100% Scolarité + 117 000 ¥/mois + Billet",
    deadline_month: "Mai",
    language_requirements: "Japonais N5 souhaité ou anglais B2",
    annual_cost_xaf: 0,
    fully_funded: true,
  },
  {
    title: "Invest Your Talent in Italy",
    country: "Italie",
    institution: "Universités publiques italiennes",
    degree_levels: ["Master"],
    eligible_fields: ["Informatique", "Génie Civil", "Business", "Sciences Économiques", "Logistique & Transport"],
    min_gpa_20: 12.5,
    max_age: 30,
    funding_coverage: "100% Scolarité + Allocation mensuelle 900 €",
    deadline_month: "Février",
    language_requirements: "Anglais B2 (IELTS 5.5 min.)",
    annual_cost_xaf: 0,
    fully_funded: true,
  },
  {
    title: "Bourse AMCI — Agence Marocaine de Coopération",
    country: "Maroc",
    institution: "Universités publiques marocaines",
    degree_levels: ["Licence", "Master"],
    eligible_fields: ["Médecine", "Pharmacie", "Droit", "Sciences Économiques", "Informatique", "Génie Civil"],
    min_gpa_20: 12.0,
    max_age: 23,
    funding_coverage: "100% Scolarité + 750 MAD/mois + Logement",
    deadline_month: "Juin",
    language_requirements: "Français courant",
    annual_cost_xaf: 0,
    fully_funded: true,
  },
  {
    title: "DAAD — EPOS Development-Related Postgraduate",
    country: "Allemagne",
    institution: "Universités allemandes partenaires",
    degree_levels: ["Master", "Doctorat"],
    eligible_fields: ["Agronomie", "Sciences de l'Environnement", "Sciences Économiques", "Logistique & Transport", "Sciences de l'Éducation"],
    min_gpa_20: 14.0,
    max_age: 36,
    funding_coverage: "100% Scolarité + 992 €/mois + Assurance",
    deadline_month: "Août",
    language_requirements: "Anglais C1 ou allemand B2",
    annual_cost_xaf: 0,
    fully_funded: true,
  },
  {
    title: "Bourse Eiffel — Campus France",
    country: "France",
    institution: "Grandes écoles et universités françaises",
    degree_levels: ["Master", "Doctorat"],
    eligible_fields: ["Informatique", "Génie Civil", "Droit", "Sciences Économiques", "Business"],
    min_gpa_20: 14.5,
    max_age: 30,
    funding_coverage: "1 181 €/mois + Billet + Couverture sociale",
    deadline_month: "Janvier",
    language_requirements: "Français C1 ou anglais C1",
    annual_cost_xaf: 0,
    fully_funded: true,
  },
  {
    title: "Chinese Government Scholarship — CSC",
    country: "Chine",
    institution: "Universités chinoises accréditées",
    degree_levels: ["Licence", "Master", "Doctorat"],
    eligible_fields: ["Informatique", "Génie Civil", "Génie Électrique", "Médecine", "Business", "Agronomie"],
    min_gpa_20: 12.5,
    max_age: 35,
    funding_coverage: "100% Scolarité + Logement + 2 500 ¥/mois",
    deadline_month: "Avril",
    language_requirements: "Chinois (année de langue offerte) ou anglais B2",
    annual_cost_xaf: 0,
    fully_funded: true,
  },
  {
    title: "Hungary Stipendium Hungaricum",
    country: "Hongrie",
    institution: "Universités publiques hongroises",
    degree_levels: ["Licence", "Master", "Doctorat"],
    eligible_fields: ["Médecine", "Informatique", "Génie Civil", "Agronomie", "Sciences Économiques"],
    min_gpa_20: 13.0,
    max_age: null,
    funding_coverage: "100% Scolarité + Logement + Allocation",
    deadline_month: "Janvier",
    language_requirements: "Anglais B2",
    annual_cost_xaf: 0,
    fully_funded: true,
  },
  {
    title: "Mastercard Foundation Scholars — ALU",
    country: "Rwanda",
    institution: "African Leadership University",
    degree_levels: ["Licence"],
    eligible_fields: ["Business", "Informatique", "Sciences Économiques", "Communication"],
    min_gpa_20: 13.5,
    max_age: 26,
    funding_coverage: "100% Scolarité + Logement + Ordinateur + Stage",
    deadline_month: "Mars",
    language_requirements: "Anglais B2",
    annual_cost_xaf: 0,
    fully_funded: true,
  },
  {
    title: "Université Cheikh Anta Diop — Admission internationale",
    country: "Sénégal",
    institution: "UCAD Dakar",
    degree_levels: ["Licence", "Master"],
    eligible_fields: ["Droit", "Médecine", "Sciences Économiques", "Informatique", "Communication"],
    min_gpa_20: 10.5,
    max_age: null,
    funding_coverage: "Droits d'inscription réduits pour ressortissants CEDEAO",
    deadline_month: "Juillet",
    language_requirements: "Français courant",
    annual_cost_xaf: 420000,
    fully_funded: false,
  },
  {
    title: "Kenyatta University — International Merit Award",
    country: "Kenya",
    institution: "Kenyatta University",
    degree_levels: ["Licence", "Master"],
    eligible_fields: ["Business", "Sciences de l'Éducation", "Agronomie", "Communication"],
    min_gpa_20: 11.0,
    max_age: null,
    funding_coverage: "Réduction de 30% des frais internationaux",
    deadline_month: "Mars",
    language_requirements: "Anglais B1",
    annual_cost_xaf: 780000,
    fully_funded: false,
  },
  {
    title: "Cyprus International University — Merit Scholarship",
    country: "Chypre",
    institution: "CIU Nicosie",
    degree_levels: ["Licence", "Master"],
    eligible_fields: ["Informatique", "Génie Civil", "Business", "Communication", "Arts & Design"],
    min_gpa_20: 11.5,
    max_age: null,
    funding_coverage: "50% à 100% de réduction sur la scolarité",
    deadline_month: "Août",
    language_requirements: "Anglais B1 (préparatoire disponible)",
    annual_cost_xaf: 950000,
    fully_funded: false,
  },
  {
    title: "Lovely Professional University — Scholarship Scheme",
    country: "Inde",
    institution: "LPU Punjab",
    degree_levels: ["Licence", "Master"],
    eligible_fields: ["Informatique", "Génie Civil", "Business", "Pharmacie", "Agronomie"],
    min_gpa_20: 11.0,
    max_age: null,
    funding_coverage: "Réduction jusqu'à 60% + logement",
    deadline_month: "Juillet",
    language_requirements: "Anglais B1",
    annual_cost_xaf: 870000,
    fully_funded: false,
  },
  {
    title: "UCSI University — Trust Scholarship",
    country: "Malaisie",
    institution: "UCSI Kuala Lumpur",
    degree_levels: ["Licence", "Master"],
    eligible_fields: ["Informatique", "Business", "Arts & Design", "Pharmacie"],
    min_gpa_20: 12.5,
    max_age: null,
    funding_coverage: "Réduction de 30% à 100% selon la moyenne",
    deadline_month: "Août",
    language_requirements: "Anglais B2",
    annual_cost_xaf: 1700000,
    fully_funded: false,
  },
  {
    title: "2iE — Institut International d'Ingénierie",
    country: "Burkina Faso",
    institution: "Fondation 2iE Ouagadougou",
    degree_levels: ["Licence", "Master"],
    eligible_fields: ["Génie Civil", "Sciences de l'Environnement", "Génie Électrique", "Agronomie"],
    min_gpa_20: 12.5,
    max_age: null,
    funding_coverage: "Bourse partielle 30% à 80%",
    deadline_month: "Mai",
    language_requirements: "Français courant",
    annual_cost_xaf: 680000,
    fully_funded: false,
  },
  {
    title: "AIMS — African Institute for Mathematical Sciences",
    country: "Rwanda",
    institution: "AIMS Kigali",
    degree_levels: ["Master"],
    eligible_fields: ["Informatique", "Sciences Économiques", "Sciences de l'Environnement"],
    min_gpa_20: 14.0,
    max_age: 30,
    funding_coverage: "100% Scolarité + Logement + Allocation",
    deadline_month: "Février",
    language_requirements: "Anglais B2 ou français",
    annual_cost_xaf: 0,
    fully_funded: true,
  },
  {
    title: "Erasmus Mundus Joint Master",
    country: "Multi-pays",
    institution: "Consortiums universitaires européens",
    degree_levels: ["Master"],
    eligible_fields: ["Informatique", "Sciences de l'Environnement", "Sciences Économiques", "Génie Civil", "Communication"],
    min_gpa_20: 14.5,
    max_age: null,
    funding_coverage: "1 400 €/mois + Scolarité + Voyage",
    deadline_month: "Janvier",
    language_requirements: "Anglais C1",
    annual_cost_xaf: 0,
    fully_funded: true,
  },
  {
    title: "Université Laval — Exemption des droits majorés",
    country: "Canada",
    institution: "Université Laval",
    degree_levels: ["Licence", "Master"],
    eligible_fields: ["Génie Civil", "Informatique", "Droit", "Agronomie", "Sciences Économiques"],
    min_gpa_20: 12.5,
    max_age: null,
    funding_coverage: "Exemption partielle des droits internationaux",
    deadline_month: "Novembre",
    language_requirements: "Français C1",
    annual_cost_xaf: 1200000,
    fully_funded: false,
  }
];

export const FALLBACK_CATALOG: Scholarship[] = SEED.map((s, index) => ({
  ...s,
  id: `demo-${index + 1}`,
  application_url: null,
  notes: null,
  is_active: true,
  created_at: "1970-01-01T00:00:00.000Z",
}));
