-- =====================================================================
-- Travis — Seed : 50 bourses et programmes internationaux récurrents
-- Idempotent : relançable sans dupliquer les lignes (clé = title + country).
-- =====================================================================

create unique index if not exists scholarships_title_country_key
    on public.scholarships (title, country);

insert into public.scholarships
  (title, country, institution, degree_levels, eligible_fields, min_gpa_20,
   max_age, funding_coverage, deadline_month, language_requirements,
   annual_cost_xaf, fully_funded)
values
  ('Bourse du Gouvernement Turc — Türkiye Bursları', 'Turquie', 'Université d''État (réseau YÖK)', ARRAY['Licence','Master','Doctorat']::text[], ARRAY['Informatique','Génie Civil','Génie Électrique','Médecine','Business','Agronomie','Droit','Sciences Économiques']::text[], 13.00, 30, '100% Scolarité + Allocation + Logement + Billet', 'Février', 'Turc (année préparatoire offerte) ou anglais B2', 0, true),
  ('Programme MEXT — Étudiant Recherche', 'Japon', 'Universités nationales japonaises', ARRAY['Licence','Master','Doctorat']::text[], ARRAY['Informatique','Génie Civil','Génie Électrique','Agronomie','Sciences de l''Environnement']::text[], 14.00, 35, '100% Scolarité + 117 000 ¥/mois + Billet', 'Mai', 'Japonais N5 souhaité ou anglais B2', 0, true),
  ('Invest Your Talent in Italy', 'Italie', 'Universités publiques italiennes', ARRAY['Master']::text[], ARRAY['Informatique','Génie Civil','Business','Sciences Économiques','Logistique & Transport']::text[], 12.50, 30, '100% Scolarité + Allocation mensuelle 900 €', 'Février', 'Anglais B2 (IELTS 5.5 min.)', 0, true),
  ('Bourse AMCI — Agence Marocaine de Coopération', 'Maroc', 'Universités publiques marocaines', ARRAY['Licence','Master']::text[], ARRAY['Médecine','Pharmacie','Droit','Sciences Économiques','Informatique','Génie Civil']::text[], 12.00, 23, '100% Scolarité + 750 MAD/mois + Logement', 'Juin', 'Français courant', 0, true),
  ('DAAD — EPOS Development-Related Postgraduate', 'Allemagne', 'Universités allemandes partenaires', ARRAY['Master','Doctorat']::text[], ARRAY['Agronomie','Sciences de l''Environnement','Sciences Économiques','Logistique & Transport','Sciences de l''Éducation']::text[], 14.00, 36, '100% Scolarité + 992 €/mois + Assurance', 'Août', 'Anglais C1 ou allemand B2', 0, true),
  ('Bourse Eiffel — Campus France', 'France', 'Grandes écoles et universités françaises', ARRAY['Master','Doctorat']::text[], ARRAY['Informatique','Génie Civil','Droit','Sciences Économiques','Business']::text[], 14.50, 30, '1 181 €/mois + Billet + Couverture sociale', 'Janvier', 'Français C1 ou anglais C1', 0, true),
  ('Chinese Government Scholarship — CSC', 'Chine', 'Universités chinoises accréditées', ARRAY['Licence','Master','Doctorat']::text[], ARRAY['Informatique','Génie Civil','Génie Électrique','Médecine','Business','Agronomie']::text[], 12.50, 35, '100% Scolarité + Logement + 2 500 ¥/mois', 'Avril', 'Chinois (année de langue offerte) ou anglais B2', 0, true),
  ('Global Korea Scholarship — GKS', 'Corée du Sud', 'Universités coréennes partenaires', ARRAY['Licence','Master','Doctorat']::text[], ARRAY['Informatique','Génie Électrique','Business','Arts & Design','Sciences Économiques']::text[], 14.00, 25, '100% Scolarité + 900 000 KRW/mois + Billet', 'Février', 'Coréen TOPIK (année offerte) ou anglais B2', 0, true),
  ('Hungary Stipendium Hungaricum', 'Hongrie', 'Universités publiques hongroises', ARRAY['Licence','Master','Doctorat']::text[], ARRAY['Médecine','Informatique','Génie Civil','Agronomie','Sciences Économiques']::text[], 13.00, NULL, '100% Scolarité + Logement + Allocation', 'Janvier', 'Anglais B2', 0, true),
  ('Bourse du Gouvernement Roumain', 'Roumanie', 'Universités publiques roumaines', ARRAY['Licence','Master','Doctorat']::text[], ARRAY['Médecine','Pharmacie','Génie Civil','Informatique','Agronomie']::text[], 12.00, 35, '100% Scolarité + Logement + Allocation mensuelle', 'Mars', 'Roumain (année préparatoire) ou anglais B1', 0, true),
  ('Bourse du Gouvernement Polonais — NAWA', 'Pologne', 'Universités polonaises publiques', ARRAY['Master','Doctorat']::text[], ARRAY['Informatique','Génie Civil','Sciences Économiques','Sciences de l''Environnement']::text[], 13.00, NULL, '100% Scolarité + 1 500 PLN/mois', 'Mai', 'Anglais B2 ou polonais', 0, true),
  ('Mastercard Foundation Scholars — ALU', 'Rwanda', 'African Leadership University', ARRAY['Licence']::text[], ARRAY['Business','Informatique','Sciences Économiques','Communication']::text[], 13.50, 26, '100% Scolarité + Logement + Ordinateur + Stage', 'Mars', 'Anglais B2', 0, true),
  ('Mastercard Foundation Scholars — Ashesi', 'Ghana', 'Ashesi University', ARRAY['Licence']::text[], ARRAY['Informatique','Business','Génie Électrique']::text[], 14.00, 24, '100% Scolarité + Logement + Allocation', 'Janvier', 'Anglais B2', 0, true),
  ('Bourse Islamique de Développement — IsDB', 'Multi-pays', 'Universités du réseau IsDB', ARRAY['Licence','Master','Doctorat']::text[], ARRAY['Médecine','Agronomie','Génie Civil','Informatique','Sciences de l''Environnement']::text[], 13.00, 30, '100% Scolarité + Allocation + Assurance', 'Février', 'Anglais B2 ou français', 0, true),
  ('Commonwealth Shared Scholarship', 'Royaume-Uni', 'Universités britanniques partenaires', ARRAY['Master']::text[], ARRAY['Sciences de l''Environnement','Agronomie','Sciences Économiques','Sciences de l''Éducation','Logistique & Transport']::text[], 14.50, NULL, '100% Scolarité + Vol + Allocation mensuelle', 'Décembre', 'Anglais C1 (IELTS 6.5)', 0, true),
  ('Chevening Scholarship', 'Royaume-Uni', 'Toute université britannique', ARRAY['Master']::text[], ARRAY['Droit','Business','Communication','Sciences Économiques','Sciences de l''Éducation']::text[], 15.00, NULL, '100% Scolarité + Allocation + Billets', 'Novembre', 'Anglais C1 (IELTS 6.5) + 2 ans d''expérience', 0, true),
  ('Bourse Canadienne de la Francophonie — PCBF', 'Canada', 'Universités canadiennes francophones', ARRAY['Master','Doctorat']::text[], ARRAY['Sciences de l''Éducation','Agronomie','Droit','Sciences Économiques','Sciences de l''Environnement']::text[], 14.00, 45, '100% Scolarité + Allocation + Billet', 'Octobre', 'Français C1', 0, true),
  ('Bourse d''Excellence de l''UEMOA', 'Sénégal', 'Universités de l''espace UEMOA', ARRAY['Licence','Master']::text[], ARRAY['Agronomie','Sciences Économiques','Droit','Informatique','Logistique & Transport']::text[], 13.00, 28, '100% Scolarité + Allocation trimestrielle', 'Juillet', 'Français courant', 0, true),
  ('Bourse du Gouvernement Égyptien — Al-Azhar & AUC', 'Égypte', 'Universités égyptiennes', ARRAY['Licence','Master']::text[], ARRAY['Médecine','Pharmacie','Droit','Communication','Sciences de l''Éducation']::text[], 12.00, 28, '100% Scolarité + Logement universitaire', 'Mai', 'Arabe ou anglais B1', 0, true),
  ('Bourse d''Excellence Tunisienne', 'Tunisie', 'Universités publiques tunisiennes', ARRAY['Licence','Master']::text[], ARRAY['Médecine','Génie Civil','Informatique','Pharmacie']::text[], 12.50, 26, 'Scolarité offerte + Logement subventionné', 'Juin', 'Français courant', 0, true),
  ('Université Cheikh Anta Diop — Admission internationale', 'Sénégal', 'UCAD Dakar', ARRAY['Licence','Master']::text[], ARRAY['Droit','Médecine','Sciences Économiques','Informatique','Communication']::text[], 10.50, NULL, 'Droits d''inscription réduits pour ressortissants CEDEAO', 'Juillet', 'Français courant', 420000, false),
  ('Université Mohammed VI Polytechnique — Bourse partielle', 'Maroc', 'UM6P Benguérir', ARRAY['Licence','Master']::text[], ARRAY['Informatique','Génie Électrique','Agronomie','Sciences de l''Environnement']::text[], 14.00, NULL, 'Jusqu''à 70% des frais + logement', 'Avril', 'Anglais B2 ou français C1', 900000, false),
  ('Kenyatta University — International Merit Award', 'Kenya', 'Kenyatta University', ARRAY['Licence','Master']::text[], ARRAY['Business','Sciences de l''Éducation','Agronomie','Communication']::text[], 11.00, NULL, 'Réduction de 30% des frais internationaux', 'Mars', 'Anglais B1', 780000, false),
  ('Strathmore University — African Leaders Award', 'Kenya', 'Strathmore University', ARRAY['Licence']::text[], ARRAY['Business','Informatique','Sciences Économiques']::text[], 13.00, 25, 'Réduction de 50% + mentorat', 'Avril', 'Anglais B2', 1150000, false),
  ('University of Pretoria — Commonwealth Africa Bursary', 'Afrique du Sud', 'University of Pretoria', ARRAY['Master']::text[], ARRAY['Sciences de l''Environnement','Agronomie','Droit','Sciences Économiques']::text[], 13.50, NULL, 'Scolarité partiellement couverte', 'Septembre', 'Anglais B2', 1400000, false),
  ('Université Internationale de Rabat — Mérite', 'Maroc', 'UIR Rabat', ARRAY['Licence','Master']::text[], ARRAY['Génie Civil','Informatique','Business','Droit']::text[], 13.00, NULL, 'Bourse de mérite de 25% à 60%', 'Juin', 'Français C1', 1600000, false),
  ('Cyprus International University — Merit Scholarship', 'Chypre', 'CIU Nicosie', ARRAY['Licence','Master']::text[], ARRAY['Informatique','Génie Civil','Business','Communication','Arts & Design']::text[], 11.50, NULL, '50% à 100% de réduction sur la scolarité', 'Août', 'Anglais B1 (préparatoire disponible)', 950000, false),
  ('Istanbul Aydin University — Bourse internationale', 'Turquie', 'Istanbul Aydin University', ARRAY['Licence','Master']::text[], ARRAY['Informatique','Business','Arts & Design','Communication','Génie Électrique']::text[], 11.00, NULL, '25% à 75% de réduction', 'Septembre', 'Anglais B1 ou turc', 1250000, false),
  ('Lovely Professional University — Scholarship Scheme', 'Inde', 'LPU Punjab', ARRAY['Licence','Master']::text[], ARRAY['Informatique','Génie Civil','Business','Pharmacie','Agronomie']::text[], 11.00, NULL, 'Réduction jusqu''à 60% + logement', 'Juillet', 'Anglais B1', 870000, false),
  ('Amity University — International Merit', 'Inde', 'Amity University', ARRAY['Licence','Master']::text[], ARRAY['Informatique','Business','Droit','Communication']::text[], 11.50, NULL, 'Réduction de 30% à 50%', 'Juin', 'Anglais B1', 1050000, false),
  ('UCSI University — Trust Scholarship', 'Malaisie', 'UCSI Kuala Lumpur', ARRAY['Licence','Master']::text[], ARRAY['Informatique','Business','Arts & Design','Pharmacie']::text[], 12.50, NULL, 'Réduction de 30% à 100% selon la moyenne', 'Août', 'Anglais B2', 1700000, false),
  ('Limkokwing University — Africa Merit Award', 'Malaisie', 'Limkokwing University', ARRAY['Licence']::text[], ARRAY['Arts & Design','Communication','Informatique','Business']::text[], 11.00, NULL, 'Réduction de 25% à 50%', 'Septembre', 'Anglais B1', 1450000, false),
  ('Université Senghor d''Alexandrie', 'Égypte', 'Université Senghor', ARRAY['Master']::text[], ARRAY['Sciences de l''Éducation','Sciences Économiques','Sciences de l''Environnement','Communication']::text[], 13.50, 35, '100% Scolarité + Allocation + Logement', 'Janvier', 'Français C1', 0, true),
  ('2iE — Institut International d''Ingénierie', 'Burkina Faso', 'Fondation 2iE Ouagadougou', ARRAY['Licence','Master']::text[], ARRAY['Génie Civil','Sciences de l''Environnement','Génie Électrique','Agronomie']::text[], 12.50, NULL, 'Bourse partielle 30% à 80%', 'Mai', 'Français courant', 680000, false),
  ('Université Euromed de Fès — Bourse Afrique', 'Maroc', 'UEMF Fès', ARRAY['Licence','Master']::text[], ARRAY['Génie Civil','Informatique','Droit','Business','Arts & Design']::text[], 13.00, NULL, 'Bourse Afrique jusqu''à 80%', 'Juillet', 'Français C1', 1100000, false),
  ('Bourse Orange Digital Center', 'Multi-pays', 'Écoles du réseau Orange', ARRAY['Licence']::text[], ARRAY['Informatique','Communication','Génie Électrique']::text[], 12.00, 26, 'Formation intensive offerte + insertion', 'Mars', 'Français courant', 0, true),
  ('AIMS — African Institute for Mathematical Sciences', 'Rwanda', 'AIMS Kigali', ARRAY['Master']::text[], ARRAY['Informatique','Sciences Économiques','Sciences de l''Environnement']::text[], 14.00, 30, '100% Scolarité + Logement + Allocation', 'Février', 'Anglais B2 ou français', 0, true),
  ('Bourse Excellence Wallonie-Bruxelles', 'Belgique', 'Universités de la Fédération Wallonie-Bruxelles', ARRAY['Master','Doctorat']::text[], ARRAY['Médecine','Droit','Sciences Économiques','Sciences de l''Éducation','Sciences de l''Environnement']::text[], 14.00, 40, '1 200 €/mois + Scolarité + Assurance', 'Février', 'Français C1', 0, true),
  ('VLIR-UOS Master Scholarship', 'Belgique', 'Universités flamandes', ARRAY['Master']::text[], ARRAY['Agronomie','Sciences de l''Environnement','Médecine','Logistique & Transport']::text[], 14.00, 35, '100% Scolarité + Allocation + Billet', 'Février', 'Anglais B2', 0, true),
  ('Erasmus Mundus Joint Master', 'Multi-pays', 'Consortiums universitaires européens', ARRAY['Master']::text[], ARRAY['Informatique','Sciences de l''Environnement','Sciences Économiques','Génie Civil','Communication']::text[], 14.50, NULL, '1 400 €/mois + Scolarité + Voyage', 'Janvier', 'Anglais C1', 0, true),
  ('Swedish Institute Scholarships for Global Professionals', 'Suède', 'Universités suédoises', ARRAY['Master']::text[], ARRAY['Sciences de l''Environnement','Sciences Économiques','Informatique','Droit']::text[], 15.00, NULL, '100% Scolarité + 12 000 SEK/mois', 'Février', 'Anglais C1 (IELTS 6.5)', 0, true),
  ('Orange Knowledge Programme — Nuffic', 'Pays-Bas', 'Universités néerlandaises', ARRAY['Master']::text[], ARRAY['Agronomie','Sciences de l''Environnement','Sciences de l''Éducation','Logistique & Transport']::text[], 14.00, NULL, 'Scolarité + Allocation + Assurance', 'Mars', 'Anglais B2', 0, true),
  ('Université Laval — Exemption des droits majorés', 'Canada', 'Université Laval', ARRAY['Licence','Master']::text[], ARRAY['Génie Civil','Informatique','Droit','Agronomie','Sciences Économiques']::text[], 12.50, NULL, 'Exemption partielle des droits internationaux', 'Novembre', 'Français C1', 1200000, false),
  ('Université de Moncton — Bourse d''accueil', 'Canada', 'Université de Moncton', ARRAY['Licence']::text[], ARRAY['Informatique','Business','Sciences de l''Éducation','Communication']::text[], 12.00, NULL, 'Bourse d''accueil de 2 000 à 5 000 CAD', 'Février', 'Français C1', 2100000, false),
  ('Université de Sherbrooke — Bourse à la mobilité', 'Canada', 'Université de Sherbrooke', ARRAY['Master']::text[], ARRAY['Génie Civil','Informatique','Sciences de l''Environnement']::text[], 13.50, NULL, 'Exemption partielle + assistanat', 'Février', 'Français C1', 1800000, false),
  ('Politecnico di Torino — TOPoliTO', 'Italie', 'Politecnico di Torino', ARRAY['Master']::text[], ARRAY['Génie Civil','Génie Électrique','Informatique','Arts & Design']::text[], 13.50, NULL, 'Scolarité offerte + 8 000 €/an', 'Mars', 'Anglais B2', 0, true),
  ('Università di Bologna — Study Grant', 'Italie', 'Università di Bologna', ARRAY['Licence','Master']::text[], ARRAY['Droit','Sciences Économiques','Communication','Informatique']::text[], 13.00, NULL, '11 000 € + exonération des frais', 'Mars', 'Italien B1 ou anglais B2', 0, true),
  ('Université de Sfax — Coopération Afrique', 'Tunisie', 'Université de Sfax', ARRAY['Licence','Master']::text[], ARRAY['Génie Civil','Informatique','Agronomie','Sciences Économiques']::text[], 11.50, NULL, 'Frais réduits + logement universitaire', 'Juin', 'Français courant', 380000, false),
  ('American University in Cairo — African Graduate Fellowship', 'Égypte', 'AUC Le Caire', ARRAY['Master']::text[], ARRAY['Business','Communication','Sciences Économiques','Informatique']::text[], 14.50, NULL, '100% Scolarité + Logement + Allocation', 'Janvier', 'Anglais C1 (TOEFL 88)', 0, true),
  ('Abu Dhabi University — International Excellence', 'Émirats Arabes Unis', 'Abu Dhabi University', ARRAY['Licence','Master']::text[], ARRAY['Business','Informatique','Génie Civil','Logistique & Transport']::text[], 14.00, NULL, 'Réduction de 35% à 100%', 'Juillet', 'Anglais B2 (IELTS 6.0)', 2400000, false)
on conflict (title, country) do update set
  institution           = excluded.institution,
  degree_levels         = excluded.degree_levels,
  eligible_fields       = excluded.eligible_fields,
  min_gpa_20            = excluded.min_gpa_20,
  max_age               = excluded.max_age,
  funding_coverage      = excluded.funding_coverage,
  deadline_month        = excluded.deadline_month,
  language_requirements = excluded.language_requirements,
  annual_cost_xaf       = excluded.annual_cost_xaf,
  fully_funded          = excluded.fully_funded;
